language: c

matrix:
    include:
        - env: test="x64 4.8.4 (cmake)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir build1
              - cd build1
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir build2
              - cd build2
              - cmake ..
          script:  mak
addons:
    apt:
        packages:
            - cmake
