language: c
#sudo: true

matrix:
    include:
        - env: test="x64 4.8.4 (cmake)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir build1
              - cd build1
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir build2
              - cd build2
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake ninja)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir build3
              - cd build3
              # this requires sudo for some reason
              - cmake .. -GNinja
          script:  autoninja -C build.ninja
addons:
    apt:
        packages:
            - cmake
            - ninja-build
