language: 
  - c
  - android

matrix:
    include:
        - env: test="x64 4.8.4 (cmake)"
          os: linux
          dist: trusty
          language: c
          compiler: gcc
          before_script:
              - mkdir build1
              - cd build1
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake)"
          os: linux
          dist: trusty
          language: c
          compiler: clang
          before_script:
              - mkdir build2
              - cd build2
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake ninja)"
          os: linux
          dist: trusty
          language: c
          compiler: clang
          before_script:
              - mkdir build3
              - cd build3
              - cmake .. -GNinja
          script:  ninja

        - env: test="x64 5.0 (cmake android)"
          os: linux
          dist: trusty
          language: android
          sudo: true
          install: 
              - echo y | sdkmanager "ndk-bundle"
          before_script:
              - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
              - mkdir build4
              - cd build4
              - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-15 -DANDROID_ABI=armeabi-v7a ..
          script:  make

addons:
    apt:
        packages:
            - cmake
            - ninja-build
