language: c

matrix:
    include:
        - env: test="x64 4.8.4 (cmake)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir build
              - cd build
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir build
              - cd build
              - cmake ..
          script:  make

        - env: test="x64 5.0 (cmake ninja)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir build
              - cd build
              - cmake .. -GNinja
          script:  autoninja
addons:
    apt:
        packages:
            - cmake
            - ninja
